# Website details
name: 1 Post por Ano
description: A arte de demorar 1 ano para postar algo
email: tacsio@hotmail.com
author: tacsio
lang: en
locale: en_US

# Jekyll
paginate: 8
highlighter: rouge
markdown: kramdown
plugins: [jekyll-paginate]
timezone: America/Recife
paginateLabel: page
paginate_path: "page/:num"
permalink: /:categories/:year/:title
baseurl: https://tacsio.github.io/blog

#rss
url: https://tacsio.github.io/blog
rss_name: feed.xml

# Includes
addthisId: ""
disqusUsername: ""
googleAnalyticsId: "UA-153069019-1"

# Search engine verifications
bing: ""
yandex: ""
google: ""

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/404.html"
  include_posts:
    - "/index.html"
  change_frequency_name: "daily"
  priority_name: "1.00"

theme: jekyll-theme-cayman
